name: Action Using Push Files
run-name: ${{ github.actor }} run of Second Actions Demo
on: [workflow_dispatch]
jobs:
  Example-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v33
        id: changed-files

      - run: touch changed-file-list.txt

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" >> changed-file-list.txt
          done

      - name: Upload changed files list
        uses: actions/upload-artifact@v3
        with:
          name: changed-file-list
          path: changed-file-list.txt
